name:                orderbook
version:             0.1.0.0
github:              "runeksvendsen/orderbook"
license:             BSD3
author:              "Rune K. Svendsen"
maintainer:          "example@example.com"
copyright:           "2018 Rune K. Svendsen"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Type safe orderbook
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/orderbook#readme>

default-extensions:
- StrictData
- BangPatterns
- NoImplicitPrelude
- ScopedTypeVariables
- MultiParamTypeClasses
- ScopedTypeVariables
- OverloadedStrings
- KindSignatures
- DataKinds
- FlexibleInstances
- DeriveGeneric
- RecordWildCards
- DuplicateRecordFields
- FlexibleContexts
- DeriveFunctor
- TypeOperators

dependencies:
- base
- protolude
- safe-money
- vector
- text
- aeson

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fno-warn-name-shadowing

tests:
  orderbook-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-name-shadowing
    dependencies:
    - orderbook
    - QuickCheck
    - hspec
    - HUnit
    - tasty
    - tasty-smallcheck
    - tasty-quickcheck
    - smallcheck
    - hspec-smallcheck
    - hspec-expectations-pretty-diff
